version: '3'
services:
  svc:
    image: "so-vits-svc-tutorial:4.1.58"
    ipc: host
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./storage:/workspace/storage
  svc-arm64:
    image: "so-vits-svc-tutorial-arm:4.1.58"
    ipc: host
    build:
      context: .
      dockerfile: DockerfileArm
    stdin_open: true
    tty: true
    volumes:
      - ./storage:/workspace/storage